- name: nodejs
  hosts: all
  become: true
  tasks:
    - name: Install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: Copy mongodb repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install Mongo Shell
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: installed

    - name: Load Schema
      ansible.builtin.shell: mongosh --host 172.31.16.189 </app/db/master-data.js

